#!/bin/sh

function run {
        echo ">" $1
        echo
        $1
        echo
        echo
        echo
}


echo "### Minimal example "
echo 
run "./ex01_minimal_usage --n-frames=20"


echo "### Throws without the default value"  
echo
run "./ex01_minimal_usage"


echo "### With default value"  
echo
run "./ex02_default_value --n-frames=20"
run "./ex02_default_value"


echo "### Several options can be specified in the arbitrary sequence"
echo
run "./ex03_several_options --n-frames=20 --min-e-pt=8.2 --out-file=trololo.root"
run "./ex03_several_options --out-file=trololo.root --min-e-pt=8.2 --n-frames=20"


echo "### Generating help"
echo
run "./ex04_print_help"


echo "### Help option"
echo
run "./ex05_help_option --help=1"
run "./ex05_help_option --help"


echo "### OptionSwitch"
echo
run "./ex06_option_switch --help"


echo "### Adding member functions to the optons"
echo
run "./ex07_handle_help --help"


echo "### Chained notation"
echo
run "./ex08_chained_notation --out-file=trololo.root --min-e-pt=8.2 --n-frames=20"


echo "### Tuple of options"
echo
run "./ex09_tuple_of_options --out-file=trololo.root --n-frames=20"

echo "### Tuple containing another tupule(s) of options"
echo
run "./ex10_appending_a_tuple_of_options --out-file=trololo.root --n-frames=20 --min-e-pt=8.2"

echo "### Validity check: trivial example"
echo
run "./ex01_minimal_usage  --n-frames=-20"
run "./ex11_validity_check --n-frames=-20"
run "./ex11_validity_check --n-frames=20"

echo "### Validity check: realistic example"
echo
run "./ex12_advanced_validity_check --help"
run "./ex12_advanced_validity_check --uniform-field 5.4"
run "./ex12_advanced_validity_check --field-map=~/analysis/field_map.dat"
run "./ex12_advanced_validity_check --uniform-field 5.4 --field-map=~/analysis/field_map.dat"


echo "### Post-processing"
echo
run "./ex13_post-processing --help"
run "./ex13_post-processing --data-dir=/data/users/sorokin/010_updated_geo/planez_1080_1640_20_20"
run "./ex13_post-processing --data-dir=/data/users/sorokin/010_updated_geo/planez_1080_1640_20_20 --in-file=other_data.root"
run "./ex13_post-processing --data-dir=/data/users/sorokin/010_updated_geo/planez_1080_1640_20_20 --in-file=/data/users/sorokin/010_updated_geo/other_data.root"



